### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by MarkMeiji** [rathkey11/IC-Mod-Hub#1]
First I want to start off saying Thank You! To you, Rathkey. This project has been amazing and an instrumental improvement to the game in my opinion. Many not even hacks but just plain and simple quality of life improvements. I was hoping you could take some time to answer a few questions, since I am new to this kind of stuff and just not sure how things work.

1: When the game is updated, such as by steam, will I need to rerun and import these BepInEx stuff all over again, or will it not need reconfiguring every update?

2: The area quest rewards states you need a champion that increases it, such as Hew Maan, but alternatively, if one is running a fast core where Quest/Kill progress is buffed at all times, would you still need Hew Maan or any champion for that matter related to reduction/bonuses.

3: Is there any way to freeze the potion timer or amounts using this? IT would be nice to have a permanent gem hunter on.

Thank you for your time.

**Comment by rathkey11** [comment]
Appreciate the kind words.

1. When the game version is updated, the mods should still work unless there is some game code changes that affect the code the mod is reading. You shouldn't need to run or update BepInEx other than the initial installation.

2. Fast core will work. If you've piped the fast core to drop more quest items, you shouldn't need a hero like Hew or Virgil.

3. This used to be possible. I had a test account with a single gem hunter that had over 700 days of time remaining. Potion timers now use server time and can't be modified to my knowledge.

If a mod you are using is no longer working, let me know and I'll do my best to update it. While I no longer actively play the game, I do still work on more mods in my spare time. rathkey on Discord as well as the idledragons server.
